services:
  database:
    image: postgres:15
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pws

  # cache:
  #   image: redis:latest
  #   container_name: cache
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   env_file:
  #     - .env

# worker:
  #   build: .
  #   depends_on:
  #     - cache
  #     - database
  #   command: /docker-entrypoint.sh worker
  #   env_file:
  #     - .env

  # scheduler:
  #   build: .
  #   command: /docker-entrypoint.sh scheduler
  #   env_file:
  #     - .env

  migrations:
    build: .
    container_name: migrations
    restart: "no"
    depends_on:
      - database
    command: /docker-entrypoint.sh  migrations
    env_file:
      - .env
    networks:
      - pws

  createsuperuser:
    build: .
    restart: "no"
    depends_on:
      - migrations
    command: /docker-entrypoint.sh  createsuperuser
    env_file:
      - .env
    networks:
      - pws
      
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - migrations
    env_file:
      - .env
    networks:
      - pws
    volumes:
      - .:/app

networks:
  pws:
    driver: bridge

volumes:
  postgres_data:
