# Generated by Django 3.1.13 on 2021-08-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WritingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('academic_level', models.CharField(choices=[('SELECT_HERE', 'Academic Level'), ('HIGH_SCHOOL', 'High School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University')], default='SELECT_HERE', max_length=128, verbose_name='Academic Level')),
                ('service_type', models.CharField(choices=[('SELECT_HERE', 'Service Type'), ('Assignment', 'Assignment'), ('Dissertation', 'Dissertation'), ('Essay', 'Essay'), ('Proposal', 'Proposal'), ('Report', 'Report'), ('Other', 'Other')], default='SELECT_HERE', max_length=128, verbose_name='Service Type')),
                ('word_count', models.CharField(choices=[('SELECT_HERE', 'Word Count'), ('1-1000', '1-1000'), ('1001-2000', '1001-2000'), ('2001-3000', '2001-3000'), ('3001-4000', '3001-4000'), ('4001-5000', '4001-5000'), ('5000-10000', '5000-10000'), ('10000+', '10000+')], default='SELECT_HERE', max_length=128, verbose_name='Word Count')),
            ],
        ),
    ]
