# Generated by Django 3.1.13 on 2021-09-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210909_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='review',
            name='order_id',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
