# Generated by Django 3.1.13 on 2021-09-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210917_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_img',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
