# Generated by Django 3.1.13 on 2021-11-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_review_rating_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingmodel',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
