# Generated by Django 3.1.13 on 2021-08-11 16:00

import cms.models.pluginmodel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pwa_slider', serialize=False, to='cms.cmsplugin')),
                ('slider_thumb_id', models.CharField(blank=True, max_length=128, null=True)),
                ('use_simple_settings', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pwa_slide', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to=cms.models.pluginmodel.get_plugin_media_path, verbose_name='image')),
                ('url', models.CharField(blank=True, help_text='If present, clicking on image will take user to link.', max_length=255, null=True, verbose_name='link')),
                ('caption', models.TextField(blank=True, help_text='Specifies text that occurs on the slide.', max_length=255, null=True, verbose_name='caption')),
                ('page_link', models.ForeignKey(blank=True, help_text='If present, clicking on image will take user to specified page.', limit_choices_to={'publisher_is_draft': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page', verbose_name='page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
