# Generated by Django 3.1.13 on 2021-08-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('pwa', '0002_auto_20210811_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('html', models.TextField(blank=True, verbose_name='HTML')),
                ('template', models.CharField(blank=True, help_text='Enter a template (e.g. "snippets/plugin_xy.html") to be rendered. If "template" is given, the contents of field "HTML" will be passed as template variable {{ html }} to the template. Otherwise, the content of "HTML" is rendered.', max_length=255, verbose_name='Template')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Snippet',
                'verbose_name_plural': 'Snippets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SnippetPtr',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pwa_snippetptr', serialize=False, to='cms.cmsplugin')),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwa.snippet')),
            ],
            options={
                'verbose_name': 'Snippet Ptr',
                'verbose_name_plural': 'Snippet Ptrs',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
